[package]
name = "mntn"
version = "0.1.0"
authors = ["Dirk Gadsden <dirk@esherido.com>"]

[dependencies]
freetype = { git = "https://github.com/servo/rust-freetype", rev = "d564ff9" }

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.5.0"
